export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

//USER
export const USER_AUTH_SUCCESSFUL = 'USER_AUTH_SUCCESSFUL'
export const USER_AUTH_UNSUCCESSFUL = 'USER_AUTH_UNSUCCESSFUL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH ERROR'

//VENDOR
export const SS_ADDED_SUCCESSFUL = 'SS_ADDED_SUCCESSFUL'
export const SS_ADDED_UNSUCCESSFUL = 'SS_ADDED_UNSUCCESSFUL'