export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

//USER
export const USER_AUTH_SUCCESSFUL = 'USER_AUTH_SUCCESSFUL'
export const USER_AUTH_UNSUCCESSFUL = 'USER_AUTH_UNSUCCESSFUL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH ERROR'

//VENDOR
export const SS_ADDED_SUCCESSFUL = 'SS_ADDED_SUCCESSFUL'
export const SS_ADDED_UNSUCCESSFUL = 'SS_ADDED_UNSUCCESSFUL'

//Admin
export const GET_REQUEST_SUCCESSFULL = 'GET_REQUEST_SUCCESSFULL'
export const GET_REQUEST_UNSUCCESSFULL = 'GET_REQUEST_UNSUCCESSFULL'
export const GET_APPROVED_SS_SUCCESSFULL = 'GET_APPROVED_SS_SUCCESSFULL'
export const GET_APPROVED_SS_UNSUCCESSFULL = 'GET_APPROVED_SS_UNSUCCESSFULL'
export const GET_REGISTERED_USERS_SUCCESSFULL = 'GET_REGISTERED_USERS_SUCCESSFULL'
export const GET_REGISTERED_USERS_UNSUCCESSFULL = 'GET_REGISTERED_USERS_UNSUCCESSFULL'

